name: Train Model

on:
  workflow_dispatch:
    inputs:
      manual_deploy:
        description: "Manual Deploy"
        required: true
        type: boolean
        default: true
  push:
    branches:
      - main

jobs:
  run-python-script:
    name: Train Model
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('training/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        if [ -f training/requirements.txt ]; then pip install -r training/requirements.txt; fi

    - name: Run Python script
      run: |
        python training/model_training_service.py

    - name: Use the variables
      run: |
        echo "MODEL is $MODEL"
        FILE_NAME=$(basename "$PATH")
        echo "FILE NAME is $FILE_NAME"
